import net.darkhax.curseforgegradle.TaskPublishCurseForge

plugins {
    id 'fabric-loom'
    id 'multiloader-loader'
    id 'net.darkhax.curseforgegradle' version '1.1.28'
    id 'com.modrinth.minotaur' version '2.+'
}

loom {
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('run')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('run')
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.mappings_mc_version}:${project.mappings_date}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    compileOnly group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
}

tasks.named('jar', Jar) {
    dependsOn 'processDocs'
}

tasks.register('processDocs', Copy) {
    from(file("$rootDir/doc/")) {
        include '*.html'
        expand 'version': project.version,
                'date': new Date().format(project.dateFormat),
                'mcversion': project.minecraft_version,
                'loaderversion': project.fabric_version,
                'loadername': 'Fabric'
    }
    into "${layout.buildDirectory.get()}/doc"
}

if (!project.hasProperty('curseForgeApiKey')) {
    ext.curseForgeApiKey = project.findProperty('curseforge_api_key') ?: 'notset'
}
if (!project.hasProperty('modrinthApiKey')) {
    ext.modrinthApiKey = project.findProperty('modrinth_api_key') ?: 'notset'
}

tasks.register('publishCurseForge', TaskPublishCurseForge) {
    apiToken = "${curseForgeApiKey}"
    def mainFile = upload(curseforge_project_id, tasks.named('remapJar'))
    mainFile.displayName = "${project.base_name}-${project.name}-${version}"
    mainFile.releaseType = release_type
    mainFile.addModLoader('Fabric', 'Quilt')
    mainFile.addJavaVersion("Java ${java_version}")
    mainFile.addGameVersion("${project.minecraft_version}")
    mainFile.changelogType = 'html'
    mainFile.changelog = file("${layout.buildDirectory.get()}/doc/changelog.html")
}

tasks.modrinth.dependsOn(tasks.build)

modrinth {
    token = "${modrinthApiKey}"
    projectId = modrinth_project_id
    versionNumber = "${version}"
    versionName = "${project.base_name}-${project.name}-${version}"
    versionType = release_type
    uploadFile = tasks.named('remapJar')
    gameVersions = ["${project.minecraft_version}"]
    loaders = ['fabric', 'quilt']
    changelog = file("${layout.buildDirectory.get()}/doc/changelog.html").exists() ? file("${layout.buildDirectory.get()}/doc/changelog.html").text : null
}
