plugins {
    id 'java-library'
    id 'idea'
    id 'maven-publish'
}

def baseName = "${project.base_name}-${project.name}"
base {
    archivesName = baseName
}
version = "${project.version}-${project.minecraft_version}"
group = project.group_id

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version as int)
    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenCentral()
    mavenLocal()
    exclusiveContent {
        forRepository {
            maven {
                name = 'Sponge'
                url = 'https://repo.spongepowered.org/repository/maven-public'
            }
        }
        filter { includeGroupAndSubgroups('org.spongepowered') }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = 'Fabric'
                url = uri('https://maven.fabricmc.net')
            }
        }
        filter {
            includeGroup('net.fabricmc')
            includeGroup('net.fabricmc.unpick')
            includeGroup('fabric-loom')
        }
    }
    exclusiveContent {
        forRepositories(
                maven {
                    name = 'ParchmentMC'
                    url = 'https://maven.parchmentmc.org/'
                },
                maven {
                    name = 'NeoForge'
                    url = 'https://maven.neoforged.net/releases'
                }
        )
        filter { includeGroup('org.parchmentmc.data') }
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = 'UTF-8'
}

jar {
    manifest {
        attributes([
                'Specification-Title'     : project.name,
                'Specification-Vendor'    : project.group_id,
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : project.group_id,
                'Implementation-Timestamp': this.getDate(),
                'Timestamp'               : System.currentTimeMillis(),
                'Built-On-Java'           : "${System.getProperty('java.vm.version')} (${System.getProperty('java.vm.vendor')})",
                'Built-On-Minecraft'      : minecraft_version
        ])
    }
}

processResources {
    var expandProps = [
            'version'          : version,
            'mod_id'           : mod_id,
            'mod_name'         : mod_name,
            'mod_author'       : mod_author,
            'minecraft_version': minecraft_version,
            'forge_version'    : forge_version,
            'fabric_version'   : fabric_version
    ]

    filesMatching(['fabric.mod.json', 'pack.mcmeta']) {
        expand expandProps
    }

    inputs.properties(expandProps)
}

// Disables Gradle's custom module metadata from being published to maven. The
// metadata includes mapped dependencies which are not reasonably consumable by
// other mod developers.
tasks.withType(GenerateModuleMetadata).configureEach {
    enabled = false
}

publishing {
    repositories {
        maven {
            name = 'CommonNetworking'
            url = uri('https://jm.gserv.me/repository/maven-releases/')

            credentials {
                username = project.findProperty('deploy.user') ?: System.getenv('DEPLOY_USER')
                password = project.findProperty('deploy.password') ?: System.getenv('DEPLOY_PASSWORD')
            }
        }
    }
}

def getDate() {
    def date = new Date()
    return date.format(project.dateFormat)
}
