# Project
version=1.0.22
group_id=mysticdrew
java_version=25

curseforge_project_id=806044
modrinth_project_id=HIuqnQpi

mappings_mc_version=26.1
#parchement_mappings_date
mappings_date=2025.10.05

# Common
minecraft_version=26.1

# Forge https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=62.0.1

# Neoforge https://neoforged.net/
neoforge_version=26.1.0.1-beta
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1-1

# Fabric https://fabricmc.net/develop/
fabric_api_version=0.144.0+26.1
fabric_loader_version=0.18.4

# Mod options
mod_name=Common Networking
mod_author=mysticdrew
mod_id=commonnetworking
base_name=common-networking
release_type=release
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.installations.paths=C:/Program Files/Eclipse Adoptium/jdk-25.0.2.10-hotspot
dateFormat=yyyy-MM-dd-HH:mm:ss
