# Project
version=1.1.0
group_id=mysticdrew
java_version=25

curseforge_project_id=806044
modrinth_project_id=HIuqnQpi

# Common
minecraft_version=26.2

# Forge https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=64.0.4

# Neoforge https://neoforged.net/
neoforge_version=26.2.0.0-beta
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-1

# Fabric https://fabricmc.net/develop/
fabric_api_version=0.152.1+26.2
fabric_loader_version=0.19.3

# Paper https://papermc.io/downloads/paper
paper_version=26.1.2.build.63-stable

# Mod options
mod_name=Common Networking
mod_author=mysticdrew
mod_id=commonnetworking
base_name=common-networking
release_type=release
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.installations.paths=C:/Program Files/Eclipse Adoptium/jdk-25.0.2.10-hotspot
dateFormat=yyyy-MM-dd-HH:mm:ss
